language: ruby
rvm: 2.5
sudo: false
cache: bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production

branches:
  only:
    - build

before_script:
  - echo "www.groveld.com" > ./src/CNAME
  - sed -i -e "s/{{ site.time }}::/${TRAVIS_COMMIT::7}::/g" ./src/sw.js
  - mv ./src/css/main.css ./src/css/main.${TRAVIS_COMMIT::7}.css
  - sed -i -e "s/main.css/main.${TRAVIS_COMMIT::7}.css/g" ./src/_layouts/default.html
  - mv ./src/css/syntax.css ./src/css/syntax.${TRAVIS_COMMIT::7}.css
  - sed -i -e "s/syntax.css/syntax.${TRAVIS_COMMIT::7}.css/g" ./src/_layouts/default.html
  - mv ./src/js/main.js ./src/js/main.${TRAVIS_COMMIT::7}.js
  - sed -i -e "s/main.js/main.${TRAVIS_COMMIT::7}.js/g" ./src/_layouts/default.html

after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email "martin@groveld.com"
  - git clone --quiet --depth=50 --branch=master https://$GITHUB_API_KEY@github.com/groveld/groveld.github.io.git ../master > /dev/null 2>&1
  - rsync -vrth --delete --exclude '.git*' ./html/ ../master/
  - cd ../master
  - git add -A .
  - git commit -am "Automated Build ($TRAVIS_COMMIT)"
  - git push -fq origin master > /dev/null 2>&1
