language: ruby
rvm: 2.5
sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - build

before_install:
  - echo "www.groveld.com" > ./src/CNAME
  # - mv ./src/public/css/app.css ./src/public/css/app.$TRAVIS_COMMIT.css
  # - mv ./src/public/js/app.js ./src/public/js/app.$TRAVIS_COMMIT.js
  # - sed -i "s/app.css/app.$TRAVIS_COMMIT.css/" ./src/_layouts/default.html
  # - sed -i "s/app.js/app.$TRAVIS_COMMIT.js/" ./src/_layouts/default.html

after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis-ci@groveld.com"
  - git clone --quiet --depth=50 --branch=master https://$GITHUB_API_KEY@github.com/groveld/groveld.github.io.git ../master > /dev/null 2>&1
  - rsync -vrth --delete --exclude '.git*' ./html/ ../master/
  - cd ../master
  - git add -A .
  - git commit -am "Automated Build ($TRAVIS_COMMIT)"
  - git push -fq origin master > /dev/null 2>&1
