language: ruby
rvm: 2.6.3
sudo: false
cache: bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production

branches:
  only:
    - build

before_script:
  - echo "www.groveld.com" > ./jekyll/CNAME
  - sed -i -e "s/{{ site.time }}::/${TRAVIS_COMMIT::7}::/g" ./jekyll/sw.js
  - mv ./jekyll/css/main.css ./jekyll/css/main.${TRAVIS_COMMIT::7}.css
  - sed -i -e "s/main.css/main.${TRAVIS_COMMIT::7}.css/g" ./jekyll/_layouts/default.html
  - mv ./jekyll/css/syntax.css ./jekyll/css/syntax.${TRAVIS_COMMIT::7}.css
  - sed -i -e "s/syntax.css/syntax.${TRAVIS_COMMIT::7}.css/g" ./jekyll/_layouts/default.html
  - mv ./jekyll/js/main.js ./jekyll/js/main.${TRAVIS_COMMIT::7}.js
  - sed -i -e "s/main.js/main.${TRAVIS_COMMIT::7}.js/g" ./jekyll/_layouts/default.html

after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email "3328493+groveld@users.noreply.github.com"
  - git clone --quiet --depth=50 --branch=master https://$GITHUB_API_KEY@github.com/groveld/groveld.github.io.git ../master > /dev/null 2>&1
  - rsync -vrth --delete --exclude ".git*" ./html/ ../master/
  - cd ../master
  - git add -A .
  - git commit -am "Automated Build ($TRAVIS_COMMIT)"
  - git push -fq origin master > /dev/null 2>&1
