language: ruby
cache: bundler
sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - develop

before_install:
  - mv jekyll/static/stylesheet.css jekyll/static/$TRAVIS_COMMIT.css
  - mv jekyll/static/javascript.js jekyll/static/$TRAVIS_COMMIT.js
  - sed -i "s/stylesheet.css/$TRAVIS_COMMIT.css/" jekyll/_includes/head.html
  - sed -i "s/javascript.js/$TRAVIS_COMMIT.js/" jekyll/_includes/footer.html

after_success:
  - git clone --quiet --depth=50 --branch=master https://${GITHUB_API_KEY}@github.com/groveld/groveld.github.io.git master > /dev/null 2>&1
  - rsync -vrth --delete --exclude '.git*' html/ master/
  - cd master
  - git config user.name "TravisCI"
  - git config user.email "travis-ci@groveld.com"
  - git add -A .
  - git commit -am "Automated Build ($TRAVIS_COMMIT)"
  - git push -qu origin master > /dev/null 2>&1
