---
locale: 'en'
timezone: 'Europe/Amsterdam'
url: 'https://www.groveld.com'
permalink: '/articles/:title'

# Progressive Web App Settings
pwa_title             : 'Groveld'
pwa_themecolor        : '#1e88e5'
pwa_backgroundcolor   : '#1e88e5'

serviceworker         : true
google_analytics      : 'UA-134156954-1'
# disqus_name           : 'groveld'

# Custom Jekyll Configuration
title                 : 'Martin Groeneveld'
tagline               : 'The personal website of Martin Groeneveld'
description           : 'The personal website of Martin Groeneveld'
author                : 'Martin Groeneveld'
email                 : 'martin@groveld.com'

phone                 : '+31612345678'
address               : 'Streetname 123<br>Zipcode City<br>Country'
legal                 : '<a href="/terms">Terms</a> &bull; <a href="/privacy">Privacy</a>'

# Core Jekyll Configuration
sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

include:
  - _pages

exclude:
  - .editorconfig
  - .gh-content
  - .gh-pages
  - .github
  - .gitattributes
  - .gitignore
  - .jekyll-cache
  - .jekyll-metadata
  - _site
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md
