# Core Jekyll Configuration
locale                : 'en'
source                : 'src'
destination           : 'html'
url                   : 'https://www.groveld.com'
enforce_ssl           : 'www.groveld.com'
permalink             : '/articles/:title'
include               : ['_pages']
plugins               : []

# Progressive Web App Settings
pwa_title             : 'Groveld'
pwa_themecolor        : '#1e88e5'
pwa_backgroundcolor   : '#1e88e5'

# Custom Jekyll Configuration
title                 : 'Martin Groeneveld'
tagline               : 'Hacker, Maker, Tinkerer, Learner'
description           : 'The personal website of Martin Groeneveld'

author                : 'Martin Groeneveld'
email                 : 'martin@groveld.com'
phone                 : '+31610106931'
address               : 'De Kamp 8<br>8627SP Gauw<br>Netherlands'

legal                 : '<a href="/terms">Terms</a> &bull; <a href="/privacy">Privacy</a>'
google_analytics      : 'UA-134156954-1'
