# Core Jekyll Configuration
source                : src
destination           : public
url                   : https://www.groveld.com
enforce_ssl           : www.groveld.com
permalink             : /articles/:title
include               : ["_pages"]
plugins               : ["jekyll-assets", "bootstrap"]

# Custom Jekyll Configuration
title                 : Martin Groeneveld
tagline               : Opensource, security and development
description           : The personal website of Martin Groeneveld
author                : groveld
email                 : martin@groveld.com
phone                 : "+31610106931"
address               : De Kamp 8<br>8627SP Gauw<br>Netherlands
legal                 : <a href="/legal/terms">Terms</a> &bull; <a href="/legal/privacy">Privacy</a> &bull; <a href="/legal/cookies">Cookies</a>
google_analytics      : UA-47976921-1

# Plugin: Jekyll Assets
assets:
  compression: true
  gzip: false
  caching:
    enabled: true
  defaults:
    js: { integrity: true }
    css: { integrity: true }
    img: { integrity: false }
