# Core Jekyll Configuration
locale                : en
source                : src
destination           : public
url                   : https://www.groveld.com
enforce_ssl           : www.groveld.com
permalink             : /articles/:title
include               : ["_pages"]
plugins               : []

pwa_title             : "Groveld"
pwa_color             : "#343a40"
pwa_background        : "#fafafa"

# Custom Jekyll Configuration
title                 : Martin Groeneveld
description           : The personal website of Martin Groeneveld
author                : Martin Groeneveld
email                 : martin@groveld.com
phone                 : "+31610106931"
address               : De Kamp 8<br>8627SP Gauw<br>Netherlands
legal                 : <a href="/terms/">Terms</a> &bull; <a href="/terms/privacy">Privacy</a> &bull; <a href="/terms/cookies">Cookies</a>
# google_analytics      : UA-47976921-1
# disqus                : groveld
