name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - '_drafts/**'
  schedule:
    - cron:  '0 0 * * *'

env:
  JEKYLL_ENV: production

jobs:
  build:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Checkout Theme
        uses: actions/checkout@v2
        with:
          repository: groveld/jekyll-theme
          ref: main
          path: theme

      - name: Checkout Content
        uses: actions/checkout@v2
        with:
          ref: main
          path: content

      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: pages

      - name: Merge Content into Theme
        run: |
          rm -rf ${GITHUB_WORKSPACE}/theme/_posts/
          rsync -av --exclude ".git*" --exclude "LICENSE" --exclude "README.md" ${GITHUB_WORKSPACE}/content/ ${GITHUB_WORKSPACE}/theme/

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Jekyll
        run: |
          cd ${GITHUB_WORKSPACE}/theme/
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build Jekyll
        run: |
          cd ${GITHUB_WORKSPACE}/theme/
          bundle exec jekyll build

      - name: Validate Jekyll
        run: |
          cd ${GITHUB_WORKSPACE}/theme/
          bundle exec htmlproofer ./_site --assume_extension --check_favicon --check-html --disable_external

      - name: Prepare GitHub Pages
        run: |
          echo "www.groveld.com" > ${GITHUB_WORKSPACE}/theme/_site/CNAME
          rsync -av --delete --exclude ".git*" ${GITHUB_WORKSPACE}/theme/_site/ ${GITHUB_WORKSPACE}/pages/

      - name: Publish GitHub Pages
        run: |
          cd ${GITHUB_WORKSPACE}/pages/
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -am "Published by GitHub Actions (${GITHUB_SHA::7})"
          git push -f origin gh-pages > /dev/null 2>&1
