name: Build and deploy site to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
#       - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - '_drafts/**'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Checkout Theme
        uses: actions/checkout@v2
        with:
          repository: groveld/jekyll-theme
          ref: main
          path: theme

      - name: Checkout Content
        uses: actions/checkout@v2
        with:
          ref: main
          path: content

      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: pages

      - name: Populate Jekyll with production content
        run: |
          rm -rf ${GITHUB_WORKSPACE}/theme/_posts/
          rsync -av --exclude ".git*" --exclude "README.md" ${GITHUB_WORKSPACE}/content/ ${GITHUB_WORKSPACE}/theme/

      - name: Install Jekyll and build site
        env:
          JEKYLL_ENV: production
        run: |
          cd ${GITHUB_WORKSPACE}/theme/
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build
          # bundle exec htmlproofer ./_site --check-html --check-sri

      - name: Prepare main branch
        run: |
          echo "www.groveld.com" > ${GITHUB_WORKSPACE}/theme/_site/CNAME
          rsync -av --delete --exclude ".git*" ${GITHUB_WORKSPACE}/theme/_site/ ${GITHUB_WORKSPACE}/pages/

      - name: Publish site to GitHub
        run: |
          cd ${GITHUB_WORKSPACE}/pages/
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -am "Published by GitHub Actions (${GITHUB_SHA::7})"
          git push -f origin gh-pages > /dev/null 2>&1
