name: Build and Publish to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '_drafts/**'
      - '.gitattributes'
      - '.gitignore'
      - 'Gemfile'
      - 'LICENSE'
      - 'README.md'
  schedule:
    - cron:  '0 0 * * *'

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "jekyll"
  cancel-in-progress: false

jobs:
  build:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Theme
        uses: actions/checkout@v2
        with:
          repository: groveld/jekyll-theme
          ref: main
          
      - name: Checkout Content
        uses: actions/checkout@v2
        with:
          ref: main
          path: .gh-content

      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: .gh-pages

      - name: Merge Content and Theme
        run: |
          rm -rf ${GITHUB_WORKSPACE}/_posts/
          rsync -av --exclude ".git*" --exclude "LICENSE" --exclude "README.md" ${GITHUB_WORKSPACE}/.gh-content/ ${GITHUB_WORKSPACE}/

      - name: Install Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Build Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install PurgeCSS and remove unused CSS
        run: |
          npm i -g purgecss
          purgecss --css ${GITHUB_WORKSPACE}/_site/**/*.css --content ${GITHUB_WORKSPACE}/_site/**/*.html

      - name: Validate Jekyll
        run: bundle exec htmlproofer ${GITHUB_WORKSPACE}/_site/ --checks Images,Scripts,Favicon --disable-external

      - name: Prepare GitHub Pages
        run: |
          echo "www.groveld.com" > ${GITHUB_WORKSPACE}/_site/CNAME
          rsync -av --checksum --delete --exclude ".git*" ${GITHUB_WORKSPACE}/_site/ ${GITHUB_WORKSPACE}/.gh-pages/

      - name: Publish GitHub Pages
        run: |
          cd ${GITHUB_WORKSPACE}/.gh-pages/
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -am "Published by GitHub Actions (${GITHUB_SHA::7})"
          git push -f origin gh-pages > /dev/null 2>&1
