name: Build and Publish to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
#       - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - '_drafts/**'
  schedule:
    - cron:  '0 0 * * *'

env:
  JEKYLL_ENV: production

jobs:
  build:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Theme
        uses: actions/checkout@v2
        with:
          repository: groveld/jekyll-theme
          ref: main
          
      - name: Checkout Content
        uses: actions/checkout@v2
        with:
          ref: main
          path: .content

      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: .pages

      - name: Merge Content and Theme
        run: |
          rm -rf ${GITHUB_WORKSPACE}/_posts/
          rsync -av --exclude ".git*" --exclude "LICENSE" --exclude "README.md" ${GITHUB_WORKSPACE}/.content/ ${GITHUB_WORKSPACE}/
          ls -lah ${GITHUB_WORKSPACE}/

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build Jekyll
        run: bundle exec jekyll build

      - name: Prepare GitHub Pages
        run: |
          ls -lah ${GITHUB_WORKSPACE}/_site/
          echo "www.groveld.com" > ${GITHUB_WORKSPACE}/_site/CNAME
          rsync -av --delete --exclude ".git*" ${GITHUB_WORKSPACE}/_site/ ${GITHUB_WORKSPACE}/.pages/
          ls -lah ${GITHUB_WORKSPACE}/.pages/

      - name: Publish GitHub Pages
        run: |
          cd ${GITHUB_WORKSPACE}/.pages/
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -am "Published by GitHub Actions (${GITHUB_SHA::7})"
          git push -f origin gh-pages > /dev/null 2>&1
